# Generated by Django 3.1.1 on 2020-09-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_user_is_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_professor',
            field=models.BooleanField(),
        ),
    ]
