# Generated by Django 3.1.1 on 2020-09-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200926_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_professor',
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
