# Generated by Django 3.1.1 on 2020-09-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='areaDc',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
